export const JsonExample = `{
    "deviceName": "TestDevice",
    "deviceWeight": 2.2,
    "submodules": [
        {
            "moduleName": "Module 1"
        },
        {
            "moduleName": "Module 2"
        }
    ]
}`

export const JsonSchemaExample = `{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/MyDevice",
    "definitions": {
        "MyDevice": {
            "type": "object",
            "properties": {
                "deviceName": {
                    "type": "string"
                },
                "deviceWeight": {
                    "type": "number",
                    "format": "float"
                },
                "submodules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/MyModule"
                    }
                }
            }
        },
        "MyModule": {
            "type": "object",
            "properties": {
                "moduleName": {
                    "type": "string"
                }
            }
        }
    }
}`

export const MsbSelfDescriptionExample = `{
    "@class": "Application",
    "uuid": "d33880ce-fb3f-44a4-b407-0993e123456",
    "name": "MySampleApp",
    "description": "This is my sample application generated by MSB Studio",
    "token": "1233e25ba567",
    "events": [
      {
        "@id": 1,
        "eventId": "E1",
        "name": "Event E1",
        "description": "Description for Event E1",
        "dataFormat": {
          "dataObject": {
            "$ref": "#/definitions/MyDevice"
          },
          "MyDevice": {
            "type": "object",
            "properties": {
              "deviceName": {
                "type": "string"
              },
              "deviceWeight": {
                "type": "number",
                "format": "float"
              },
              "submodules": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/MyModule"
                }
              }
            }
          },
          "MyModule": {
            "type": "object",
            "properties": {
              "moduleName": {
                "type": "string"
              }
            }
          }
        }
      },
      {
        "@id": 2,
        "eventId": "SendAnotherMessageEvent",
        "name": "Send Another Message Event",
        "description": "Event to send another message",
        "dataFormat": {
          "dataObject": {
            "$ref": "#/definitions/MessageContext"
          },
          "MessageContext": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            }
          }
        }
      }
    ],
    "functions": [
      {
        "@id": 1,
        "functionId": "F1",
        "name": "Function F1",
        "description": "Description for Function F1",
        "dataFormat": {
          "dataObject": {
            "type": "string"
          }
        }
      },
      {
        "@id": 2,
        "functionId": "handleMessage",
        "name": "Handle Message",
        "description": "Handles an incoming message",
        "dataFormat": {
          "dataObject": {
            "$ref": "#/definitions/MessageContext"
          },
          "MessageContext": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "message": {
                "type": "string"
              }
            }
          }
        },
        "responseEvents": [
          2
        ]
      }
    ],
    "configuration": {
      "parameters": {
        "confParam1": {
          "value": true,
          "type": "boolean"
        },
        "confParam2": {
          "value": "StringValue",
          "type": "string"
        },
        "confParam3": {
          "value": 1000,
          "type": "integer",
          "format": "int32"
        },
        "confParam4": {
          "value": 3.3,
          "type": "number",
          "format": "double"
        },
        "confParam5": {
          "value": "2019-07-23 11:07:00.938401",
          "type": "string",
          "format": "date-time"
        }
      }
    }
}
`
